// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT
import {main} from '../models';

export function GetHistory():Promise<Array<main.ConnectionProfile>>;

export function OpenBrowser():Promise<void>;

export function StartDeploy(arg1:string,arg2:string,arg3:string,arg4:string,arg5:string,arg6:string):Promise<void>;

export function StopDeploy():Promise<void>;
