// @ts-check
// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

export function GetHistory() {
  return window['go']['main']['App']['GetHistory']();
}

export function OpenBrowser() {
  return window['go']['main']['App']['OpenBrowser']();
}

export function StartDeploy(arg1, arg2, arg3, arg4, arg5, arg6) {
  return window['go']['main']['App']['StartDeploy'](arg1, arg2, arg3, arg4, arg5, arg6);
}

export function StopDeploy() {
  return window['go']['main']['App']['StopDeploy']();
}
